services:
  - type: web
    name: shopez-api
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install && npm run seed
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://client-nine-flame-44.vercel.app
      - key: MONGO_URI
        value: mongodb+srv://smartbridge_user:ShopEZ2024Prod@cluster0.5f1ujuq.mongodb.net/shopez?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d