const mongoose = require('mongoose');
const dotenv = require('dotenv');
const bcrypt = require('bcryptjs');

dotenv.config();

const User = require('../models/User');
const Product = require('../models/Product');
const Admin = require('../models/Admin');
const Cart = require('../models/Cart');
const Order = require('../models/Order');

const products = [
  // Electronics
  {
    title: 'Sony WH-1000XM5 Wireless Headphones',
    description: 'Industry-leading noise canceling with Auto NC Optimizer. Crystal clear hands-free calling with 4 beamforming microphones. Up to 30 hours battery life with quick charging.',
    price: 28990,
    discount: 15,
    stock: 45,
    category: 'Electronics',
    brand: 'Sony',
    images: ['https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=500', 'https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=500'],
    rating: 4.7,
    numReviews: 234,
    isFeatured: true,
    isTrending: true,
  },
  {
    title: 'Apple MacBook Air M2 13-inch',
    description: 'Supercharged by the M2 chip. Up to 18 hours of battery life. 13.6-inch Liquid Retina display with 500 nits of brightness. Fanless design for silent operation.',
    price: 114900,
    discount: 8,
    stock: 20,
    category: 'Electronics',
    brand: 'Apple',
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500', 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=500'],
    rating: 4.9,
    numReviews: 512,
    isFeatured: true,
    isTrending: true,
  },
  {
    title: 'Samsung Galaxy S24 Ultra',
    description: 'The ultimate smartphone experience with Galaxy AI. 200MP camera, titanium frame, built-in S Pen, and stunning 6.8-inch QHD+ Dynamic AMOLED display.',
    price: 129999,
    discount: 10,
    stock: 30,
    category: 'Electronics',
    brand: 'Samsung',
    images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=500'],
    rating: 4.6,
    numReviews: 389,
    isFeatured: true,
    isTrending: false,
  },
  {
    title: 'iPad Pro 12.9" M2 Chip',
    description: 'The ultimate iPad experience with the M2 chip. Liquid Retina XDR display, ProMotion, and Thunderbolt connectivity. Perfect for creative professionals.',
    price: 112900,
    discount: 5,
    stock: 15,
    category: 'Electronics',
    brand: 'Apple',
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500'],
    rating: 4.8,
    numReviews: 178,
    isFeatured: false,
    isTrending: true,
  },
  {
    title: 'JBL Charge 5 Portable Speaker',
    description: 'Powerful JBL Original Pro Sound. IP67 waterproof and dustproof. 20 hours of playtime. Built-in powerbank to charge your devices.',
    price: 14999,
    discount: 20,
    stock: 60,
    category: 'Electronics',
    brand: 'JBL',
    images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500'],
    rating: 4.5,
    numReviews: 456,
    isFeatured: false,
    isTrending: false,
  },
  // Fashion
  {
    title: 'Classic Leather Oxford Shoes',
    description: 'Handcrafted genuine leather oxford shoes with Goodyear welt construction. Premium comfort insole and durable rubber outsole. Perfect for formal and business occasions.',
    price: 4999,
    discount: 25,
    stock: 80,
    category: 'Fashion',
    brand: 'Allen Solly',
    images: ['https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=500'],
    rating: 4.3,
    numReviews: 167,
    isFeatured: true,
    isTrending: false,
  },
  {
    title: 'Premium Slim Fit Blazer',
    description: 'Tailored slim fit blazer in premium wool blend. Features notched lapels, two-button closure, and interior pockets. Available in Navy, Charcoal, and Black.',
    price: 8999,
    discount: 30,
    stock: 35,
    category: 'Fashion',
    brand: 'Raymond',
    images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=500'],
    rating: 4.4,
    numReviews: 89,
    isFeatured: true,
    isTrending: true,
  },
  {
    title: 'Casual Denim Jacket',
    description: 'Classic trucker-style denim jacket in premium washed cotton. Features button closure, chest pockets, and adjustable waist tabs. A timeless wardrobe essential.',
    price: 3499,
    discount: 15,
    stock: 100,
    category: 'Fashion',
    brand: 'Levis',
    images: ['https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=500'],
    rating: 4.5,
    numReviews: 234,
    isFeatured: false,
    isTrending: true,
  },
  {
    title: 'Women\'s Silk Wrap Dress',
    description: 'Elegant silk wrap dress with flattering fit. Features a V-neckline, self-tie waist, and flowing silhouette. Perfect for both day and evening occasions.',
    price: 5999,
    discount: 20,
    stock: 50,
    category: 'Fashion',
    brand: 'Zara',
    images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500'],
    rating: 4.6,
    numReviews: 145,
    isFeatured: true,
    isTrending: false,
  },
  {
    title: 'Premium Cotton Polo T-Shirt',
    description: 'Classic polo in breathable piqué cotton. Features ribbed collar, two-button placket, and embroidered logo. Available in 8 colors.',
    price: 1499,
    discount: 10,
    stock: 200,
    category: 'Fashion',
    brand: 'US Polo',
    images: ['https://images.unsplash.com/photo-1625910513413-5fc36e5a6e5b?w=500'],
    rating: 4.2,
    numReviews: 567,
    isFeatured: false,
    isTrending: false,
  },
  // Home & Living
  {
    title: 'Scandinavian Minimalist Desk Lamp',
    description: 'Modern desk lamp with adjustable arm and dimmable LED. Features USB charging port, touch controls, and 3 color temperature modes. Matte finish in White or Black.',
    price: 3999,
    discount: 10,
    stock: 75,
    category: 'Home & Living',
    brand: 'IKEA',
    images: ['https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=500'],
    rating: 4.4,
    numReviews: 123,
    isFeatured: true,
    isTrending: false,
  },
  {
    title: 'Organic Cotton Bedding Set',
    description: '400 thread count organic cotton bedding set. Includes fitted sheet, flat sheet, and two pillowcases. GOTS certified, hypoallergenic, and machine washable.',
    price: 6999,
    discount: 15,
    stock: 40,
    category: 'Home & Living',
    brand: 'Spaces',
    images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=500'],
    rating: 4.6,
    numReviews: 89,
    isFeatured: false,
    isTrending: true,
  },
  {
    title: 'Ceramic Dinner Set - 24 Pieces',
    description: 'Premium bone china dinner set for 6. Includes dinner plates, side plates, bowls, and mugs. Microwave and dishwasher safe with elegant gold rim design.',
    price: 4599,
    discount: 20,
    stock: 25,
    category: 'Home & Living',
    brand: 'Corelle',
    images: ['https://images.unsplash.com/photo-1603199506016-b9a694480b4e?w=500'],
    rating: 4.3,
    numReviews: 156,
    isFeatured: true,
    isTrending: false,
  },
  {
    title: 'Smart Air Purifier HEPA H13',
    description: 'Advanced air purifier with H13 True HEPA filter. Covers up to 500 sq ft. Features air quality sensor, auto mode, sleep mode, and app control.',
    price: 12999,
    discount: 12,
    stock: 30,
    category: 'Home & Living',
    brand: 'Dyson',
    images: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=500'],
    rating: 4.7,
    numReviews: 201,
    isFeatured: false,
    isTrending: true,
  },
  // Sports
  {
    title: 'Nike Air Zoom Pegasus 40',
    description: 'Responsive cushioning for everyday runs. Features Zoom Air unit, breathable mesh upper, and durable rubber outsole. Neutral support for all runners.',
    price: 11495,
    discount: 18,
    stock: 90,
    category: 'Sports',
    brand: 'Nike',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500'],
    rating: 4.6,
    numReviews: 678,
    isFeatured: true,
    isTrending: true,
  },
  {
    title: 'Yoga Mat Premium 6mm',
    description: 'Eco-friendly TPE yoga mat with alignment lines. Non-slip surface, moisture resistant, and includes carrying strap. 183cm x 61cm. Available in 6 colors.',
    price: 1999,
    discount: 10,
    stock: 150,
    category: 'Sports',
    brand: 'Boldfit',
    images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500'],
    rating: 4.4,
    numReviews: 345,
    isFeatured: false,
    isTrending: false,
  },
  {
    title: 'Adjustable Dumbbell Set 24kg',
    description: 'Space-saving adjustable dumbbells. Quick-change weight from 2.5kg to 24kg. Ergonomic handle with non-slip grip. Replaces 15 sets of weights.',
    price: 15999,
    discount: 8,
    stock: 25,
    category: 'Sports',
    brand: 'Bowflex',
    images: ['https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?w=500'],
    rating: 4.5,
    numReviews: 123,
    isFeatured: true,
    isTrending: false,
  },
  {
    title: 'Fitness Tracker Band Pro',
    description: 'Advanced fitness tracker with heart rate, SpO2, sleep tracking, and GPS. 14-day battery life, 5ATM water resistance, and 100+ workout modes.',
    price: 4999,
    discount: 25,
    stock: 70,
    category: 'Sports',
    brand: 'Fitbit',
    images: ['https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=500'],
    rating: 4.3,
    numReviews: 890,
    isFeatured: false,
    isTrending: true,
  },
  // Books
  {
    title: 'Atomic Habits by James Clear',
    description: 'An easy and proven way to build good habits and break bad ones. Tiny changes, remarkable results. One of the most impactful books on personal development.',
    price: 499,
    discount: 15,
    stock: 200,
    category: 'Books',
    brand: 'Penguin',
    images: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500'],
    rating: 4.8,
    numReviews: 2345,
    isFeatured: true,
    isTrending: true,
  },
  {
    title: 'The Psychology of Money',
    description: 'Timeless lessons on wealth, greed, and happiness by Morgan Housel. 19 short stories exploring the strange ways people think about money.',
    price: 399,
    discount: 10,
    stock: 180,
    category: 'Books',
    brand: 'Harper Business',
    images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500'],
    rating: 4.7,
    numReviews: 1567,
    isFeatured: true,
    isTrending: false,
  },
  {
    title: 'Deep Work by Cal Newport',
    description: 'Rules for focused success in a distracted world. Learn to cultivate a deep work practice and achieve extraordinary results.',
    price: 449,
    discount: 12,
    stock: 120,
    category: 'Books',
    brand: 'Piatkus',
    images: ['https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500'],
    rating: 4.5,
    numReviews: 890,
    isFeatured: false,
    isTrending: true,
  },
  // Beauty
  {
    title: 'Vitamin C Face Serum 30ml',
    description: 'Brightening face serum with 20% Vitamin C, Hyaluronic Acid, and Vitamin E. Reduces dark spots, evens skin tone, and boosts collagen production.',
    price: 899,
    discount: 30,
    stock: 100,
    category: 'Beauty',
    brand: 'Minimalist',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500'],
    rating: 4.4,
    numReviews: 567,
    isFeatured: true,
    isTrending: true,
  },
  {
    title: 'Luxury Perfume Collection Set',
    description: 'Premium fragrance discovery set with 5 x 10ml eau de parfum. Features woody, floral, citrus, oriental, and fresh scent profiles. Unisex collection.',
    price: 3999,
    discount: 15,
    stock: 45,
    category: 'Beauty',
    brand: 'Forest Essentials',
    images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=500'],
    rating: 4.6,
    numReviews: 234,
    isFeatured: false,
    isTrending: false,
  },
  {
    title: 'Professional Hair Dryer 2200W',
    description: 'Salon-grade hair dryer with ionic technology. Features 3 heat settings, 2 speed settings, cool shot button, and diffuser attachment. Lightweight design.',
    price: 2499,
    discount: 20,
    stock: 55,
    category: 'Beauty',
    brand: 'Dyson',
    images: ['https://images.unsplash.com/photo-1522338242992-e1a54571a9e7?w=500'],
    rating: 4.5,
    numReviews: 345,
    isFeatured: true,
    isTrending: false,
  },
  // Toys
  {
    title: 'LEGO Architecture Skyline Collection',
    description: 'Build iconic city skylines with this detailed LEGO Architecture set. 598 pieces, includes display nameplate. Perfect for teens and adult collectors.',
    price: 4999,
    discount: 10,
    stock: 30,
    category: 'Toys',
    brand: 'LEGO',
    images: ['https://images.unsplash.com/photo-1587654780291-39c9404d7dd0?w=500'],
    rating: 4.8,
    numReviews: 189,
    isFeatured: true,
    isTrending: true,
  },
  {
    title: 'Remote Control Racing Car',
    description: 'High-speed RC car with 2.4GHz remote control. Reaches speeds up to 30km/h. Features rechargeable battery, all-terrain tires, and LED lights.',
    price: 2999,
    discount: 15,
    stock: 65,
    category: 'Toys',
    brand: 'Hot Wheels',
    images: ['https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=500'],
    rating: 4.3,
    numReviews: 234,
    isFeatured: false,
    isTrending: false,
  },
  {
    title: 'Educational STEM Robot Kit',
    description: 'Build and program your own robot with this 400+ piece STEM kit. Compatible with Arduino. Includes sensors, motors, and step-by-step coding tutorials.',
    price: 5999,
    discount: 8,
    stock: 40,
    category: 'Toys',
    brand: 'Makeblock',
    images: ['https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=500'],
    rating: 4.6,
    numReviews: 156,
    isFeatured: false,
    isTrending: true,
  },
  // Groceries
  {
    title: 'Premium Organic Green Tea - 100 Bags',
    description: 'USDA certified organic green tea from Darjeeling. Rich in antioxidants, promotes metabolism. Individually wrapped tea bags for freshness.',
    price: 599,
    discount: 5,
    stock: 300,
    category: 'Groceries',
    brand: 'Organic India',
    images: ['https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500'],
    rating: 4.4,
    numReviews: 890,
    isFeatured: false,
    isTrending: false,
  },
  {
    title: 'Cold Pressed Extra Virgin Olive Oil 1L',
    description: 'First cold pressed from handpicked olives. Low acidity, rich flavor. Perfect for salads, cooking, and dipping. Imported from Italy.',
    price: 899,
    discount: 10,
    stock: 120,
    category: 'Groceries',
    brand: 'Borges',
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500'],
    rating: 4.5,
    numReviews: 345,
    isFeatured: true,
    isTrending: false,
  },
  {
    title: 'Assorted Dry Fruits Gift Box 1kg',
    description: 'Premium selection of almonds, cashews, pistachios, walnuts, and raisins. Beautifully packaged in an elegant gift box. Perfect for festive occasions.',
    price: 1499,
    discount: 12,
    stock: 80,
    category: 'Groceries',
    brand: 'Nutraj',
    images: ['https://images.unsplash.com/photo-1606567595334-d39972c85dbe?w=500'],
    rating: 4.6,
    numReviews: 456,
    isFeatured: true,
    isTrending: true,
  },
  // More Electronics
  {
    title: 'Mechanical Gaming Keyboard RGB',
    description: 'Full-size mechanical keyboard with Cherry MX Blue switches. Per-key RGB backlighting, aluminum frame, detachable USB-C cable, and N-key rollover.',
    price: 7999,
    discount: 22,
    stock: 50,
    category: 'Electronics',
    brand: 'Keychron',
    images: ['https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=500'],
    rating: 4.5,
    numReviews: 278,
    isFeatured: false,
    isTrending: true,
  },
  {
    title: '4K Ultra HD Smart TV 55"',
    description: 'Stunning 4K HDR display with Dolby Vision and Atmos. Built-in smart platform with all streaming apps. Voice remote control and HDMI 2.1 ports.',
    price: 42999,
    discount: 18,
    stock: 15,
    category: 'Electronics',
    brand: 'LG',
    images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500'],
    rating: 4.6,
    numReviews: 567,
    isFeatured: true,
    isTrending: false,
  },
  {
    title: 'Wireless Ergonomic Mouse',
    description: 'Ergonomic vertical mouse design reduces wrist strain. 2.4GHz wireless with USB receiver. 6 buttons, adjustable DPI, and 18-month battery life.',
    price: 1999,
    discount: 15,
    stock: 120,
    category: 'Electronics',
    brand: 'Logitech',
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500'],
    rating: 4.3,
    numReviews: 432,
    isFeatured: false,
    isTrending: false,
  },
  // More Fashion
  {
    title: 'Premium Leather Wallet',
    description: 'Genuine leather bi-fold wallet with RFID blocking. Features 8 card slots, 2 note compartments, and coin pocket. Gift boxed with dust bag.',
    price: 1299,
    discount: 20,
    stock: 150,
    category: 'Fashion',
    brand: 'Tommy Hilfiger',
    images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?w=500'],
    rating: 4.4,
    numReviews: 678,
    isFeatured: false,
    isTrending: true,
  },
  {
    title: 'Aviator Sunglasses Polarized',
    description: 'Classic aviator frame with polarized lenses. UV400 protection, anti-glare coating. Lightweight metal frame with adjustable nose pads. Includes hard case.',
    price: 2999,
    discount: 25,
    stock: 85,
    category: 'Fashion',
    brand: 'Ray-Ban',
    images: ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500'],
    rating: 4.7,
    numReviews: 890,
    isFeatured: true,
    isTrending: true,
  },
  // More Home & Living
  {
    title: 'Automatic Coffee Machine',
    description: 'Bean-to-cup automatic coffee machine with built-in grinder. Makes espresso, cappuccino, latte, and more. 15-bar pressure, milk frother, and water filter.',
    price: 34999,
    discount: 10,
    stock: 12,
    category: 'Home & Living',
    brand: 'De\'Longhi',
    images: ['https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=500'],
    rating: 4.7,
    numReviews: 234,
    isFeatured: true,
    isTrending: true,
  },
  {
    title: 'Robot Vacuum Cleaner',
    description: 'Smart robot vacuum with LiDAR navigation. 5000Pa suction, auto-empty dock, mopping function. App control, works with Alexa. 180-min runtime.',
    price: 24999,
    discount: 15,
    stock: 20,
    category: 'Home & Living',
    brand: 'iRobot',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=500'],
    rating: 4.5,
    numReviews: 345,
    isFeatured: false,
    isTrending: true,
  },
];

const categories = [
  { name: 'Electronics', image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400', description: 'Latest gadgets and devices', isActive: true },
  { name: 'Fashion', image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400', description: 'Trending styles and clothing', isActive: true },
  { name: 'Home & Living', image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=400', description: 'Furniture, decor and more', isActive: true },
  { name: 'Sports', image: 'https://images.unsplash.com/photo-1461896836934-bd45ba4a34d0?w=400', description: 'Sports gear and fitness equipment', isActive: true },
  { name: 'Books', image: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400', description: 'Best sellers and new releases', isActive: true },
  { name: 'Beauty', image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400', description: 'Skincare, makeup and fragrances', isActive: true },
  { name: 'Toys', image: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400', description: 'Fun for all ages', isActive: true },
  { name: 'Groceries', image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400', description: 'Fresh and organic products', isActive: true },
];

const banners = [
  {
    title: 'Summer Sale — Up to 50% Off',
    subtitle: 'Shop the best deals on electronics, fashion, and more',
    image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1200',
    link: '/products?sort=discount',
    isActive: true,
  },
  {
    title: 'New Arrivals in Fashion',
    subtitle: 'Discover the latest trends for the season',
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1200',
    link: '/products?category=Fashion',
    isActive: true,
  },
  {
    title: 'Tech Essentials',
    subtitle: 'Upgrade your workspace with premium gadgets',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200',
    link: '/products?category=Electronics',
    isActive: true,
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('Connected to MongoDB for seeding...');

    // Clear existing data
    await Promise.all([
      User.deleteMany({}),
      Product.deleteMany({}),
      Admin.deleteMany({}),
      Cart.deleteMany({}),
      Order.deleteMany({}),
    ]);
    console.log('Cleared existing data');

    // Create admin user
    const adminUser = await User.create({
      name: 'Admin',
      email: 'admin@shopez.com',
      password: 'admin123',
      mobile: '9999999999',
      role: 'admin',
    });
    console.log('Created admin user: admin@shopez.com / admin123');

    // Create test user
    const testUser = await User.create({
      name: 'John Doe',
      email: 'john@example.com',
      password: 'password123',
      mobile: '9876543210',
      role: 'user',
      addresses: [
        {
          fullName: 'John Doe',
          phone: '9876543210',
          street: '123 Main Street, Apt 4B',
          city: 'Mumbai',
          state: 'Maharashtra',
          zipCode: '400001',
          country: 'India',
          isDefault: true,
        },
      ],
    });
    console.log('Created test user: john@example.com / password123');

    // Create products
    await Product.insertMany(products);
    console.log(`Seeded ${products.length} products`);

    // Create admin config
    await Admin.create({
      banner: banners,
      categories: categories,
    });
    console.log('Seeded admin config (banner + categories)');

    console.log('\n✅ Database seeded successfully!');
    console.log('Admin: admin@shopez.com / admin123');
    console.log('User: john@example.com / password123');
    process.exit(0);
  } catch (error) {
    console.error('Seeding error:', error);
    process.exit(1);
  }
};

seedDB();
